name: CD
on:
  pull_request:
    branches:
    - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
          token: ${{ secrets.PAT }}
          repository: dekz/0x-main-infra
    - name: Create report file
      run: echo "${{ github.sha }}" > report.txt
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v2.3.0
      with:
          token: ${{ secrets.PAT }}
          commit-message: "[0xApi][staging] Deploy ${{ github.head_ref }}"
          title: "[0xApi][staging] Deploy ${{ github.head_ref }}"
          reviewers: dekz
          labels: 0xApi, staging
          branch: "0xApi/staging/${{ github.head_ref }}"
          body: |
            https://github.com/${{ github.repository }}/tree/${{ github.head_ref }}
            ${{ github.sha }}
    - name: Check outputs
      run: |
          echo "Pull Request Number - ${{ env.PULL_REQUEST_NUMBER }}"
          echo "Pull Request Number - ${{ steps.cpr.outputs.pr_number }}"
